name: kalshi_test_app
description: "A mobile application that uses cubit for state management, using clean architecture."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.4
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  get_it: ^7.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  coverage: ^1.0.3

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - ./assets/fonts/
    - ./assets/images/
    
  fonts:
     - family: Rubik
       fonts:
        - asset: assets/fonts/rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/rubik/Rubik-Bold.ttf
          weight: 700
        - asset: assets/fonts/rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/rubik/Rubik-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/rubik/Rubik-Black.ttf
          weight: 900
        - asset: assets/fonts/rubik/Rubik-ExtraBold.ttf
          weight: 800
     - family: WorkSans
       fonts:
        - asset: assets/fonts/worksans/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/worksans/WorkSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/worksans/WorkSans-Light.ttf
          weight: 300
        - asset: assets/fonts/worksans/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/worksans/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/worksans/WorkSans-Black.ttf
          weight: 900
        - asset: assets/fonts/worksans/WorkSans-ExtraBold.ttf
          weight: 800
